# Generated by Django 4.0.6 on 2022-07-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ManyToManyField(blank=True, null=True, related_name='brand', to='shop.brand'),
        ),
    ]
